services:
  # Backend Django
  - type: web
    name: hoolis-backend
    runtime: python
    buildCommand: |
      cd backend &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: |
      cd backend &&
      gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: hoolis.onrender.com,localhost,127.0.0.1
    
  # Frontend React
  - type: web
    name: hoolis-frontend
    runtime: node
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - source: "/index.html"
        headers:
          - key: "Cache-Control"
            value: "no-cache"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html" 