services:
  # Backend Django
  - type: web
    name: hoolis-backend
    runtime: python
    buildCommand: |
      cd backend &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='hoolis_admin').exists() or User.objects.create_superuser('hoolis_admin', 'admin@hoolis.com', 'patesaucisse91!')"
    startCommand: |
      cd backend &&
      gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: hoolis.onrender.com,localhost,127.0.0.1
    
  # Frontend React
  - type: web
    name: hoolis-frontend
    runtime: node
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - source: "/index.html"
        headers:
          - key: "Cache-Control"
            value: "no-cache"
      - source: "/static/*"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=31536000"
    routes:
      - type: redirect
        source: "/api/*"
        destination: "https://hoolis-backend.onrender.com/api/:splat"
        status: 200
      - type: rewrite
        source: "/*"
        destination: "/index.html" 