# Generated by Django 4.2.20 on 2025-08-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
