# Generated by Django 4.2.20 on 2025-06-06 16:02

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/Shop/Articles/', validators=[store.validators.validate_file_size]),
        ),
    ]
