# Generated by Django 4.2.20 on 2025-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20250806_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_payed',
            field=models.BooleanField(default=False),
        ),
    ]
