# Generated by Django 4.2.20 on 2025-06-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingwatch',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100),
        ),
    ]
