# Generated by Django 4.2.20 on 2025-06-30 15:56

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem_customer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproduct',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(default='0000000000', max_length=100, unique=True)),
        ),
        migrations.AlterField(
            model_name='bookingwatch',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(default='0000000000', max_length=100, unique=True)),
        ),
    ]
