# Generated by Django 4.2.20 on 2025-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bookingproduct_phone_bookingwatch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproduct',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingwatch',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100, unique=True),
        ),
    ]
