# Generated by Django 4.2.20 on 2025-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_has_payed_to_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('code', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
