# Generated by Django 5.0.1 on 2026-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_emailconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_resell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_resell',
            field=models.BooleanField(default=True),
        ),
    ]
