# Generated by Django 4.2.20 on 2025-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bookingproduct_phone_alter_bookingwatch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
