# Generated by Django 5.0.1 on 2026-01-24 14:04

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_collection_is_resell_product_is_resell"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmationcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/Shop/Articles/",
                validators=[store.validators.validate_image_file],
            ),
        ),
    ]
