# Generated by Django 5.0.1 on 2026-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_emailconfirmationcode_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookingProduct",
        ),
        migrations.DeleteModel(
            name="EmailConfirmationCode",
        ),
        migrations.DeleteModel(
            name="SlotsProduct",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
