# Generated by Django 5.0.1 on 2026-02-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_delete_bookingproduct_delete_emailconfirmationcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
