# Generated by Django 4.2.20 on 2025-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_booking_date_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='watch',
            field=models.CharField(default='watch', max_length=100),
        ),
    ]
