# Generated by Django 4.2.20 on 2025-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_watch_images_watchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='store/images/')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.watch')),
            ],
        ),
        migrations.DeleteModel(
            name='WatchImage',
        ),
    ]
