# Generated by Django 4.2.20 on 2025-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_watchmedia_delete_watchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmedia',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('wide', 'Wide')], default='small', max_length=100),
        ),
        migrations.AddField(
            model_name='watchmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=100),
        ),
        migrations.AlterField(
            model_name='watchmedia',
            name='media',
            field=models.FileField(upload_to='store/F&W/'),
        ),
    ]
