# Generated by Django 4.2.20 on 2026-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bg_image_desktop", models.ImageField(blank=True, upload_to="site/")),
                ("bg_image_mobile", models.ImageField(blank=True, upload_to="site/")),
            ],
            options={
                "verbose_name": "Configuration du site",
            },
        ),
    ]
