# Generated by Django 4.2.20 on 2026-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="bg_fit",
            field=models.CharField(
                choices=[
                    ("cover", "Couvrir (recadrage)"),
                    ("contain", "Contenir (image entière)"),
                    ("fill", "Étirer (remplit tout)"),
                    ("none", "Taille réelle"),
                ],
                default="cover",
                max_length=10,
                verbose_name="Ajustement de l'image",
            ),
        ),
    ]
